TRAINS = [
    {"train_no": "12301", "train_name": "Howrah Rajdhani",     "source": "NDLS", "destination": "HWH"},
    {"train_no": "12302", "train_name": "New Delhi Rajdhani",  "source": "HWH",  "destination": "NDLS"},
    {"train_no": "12951", "train_name": "Mumbai Rajdhani",     "source": "NDLS", "destination": "MMCT"},
    {"train_no": "12952", "train_name": "New Delhi Rajdhani",  "source": "MMCT", "destination": "NDLS"},
    {"train_no": "12259", "train_name": "Sealdah Duronto",     "source": "NDLS", "destination": "SDAH"},
    {"train_no": "22691", "train_name": "Rajdhani Express",    "source": "NDLS", "destination": "SBC"},
    {"train_no": "12431", "train_name": "Thiruvananthapuram",  "source": "NDLS", "destination": "TVC"},
    {"train_no": "12627", "train_name": "Karnataka Express",   "source": "NDLS", "destination": "SBC"},
    {"train_no": "11057", "train_name": "Amritsar Express",    "source": "CSTM", "destination": "ASR"},
    {"train_no": "12311", "train_name": "Kalka Mail",          "source": "HWH",  "destination": "NDLS"},
    {"train_no": "12595", "train_name": "Gorakhpur Express",   "source": "GKP",  "destination": "NDLS"},
    {"train_no": "12393", "train_name": "Sampoorna Kranti",    "source": "RJPB", "destination": "NDLS"},
    {"train_no": "12003", "train_name": "Lucknow Shatabdi",    "source": "NDLS", "destination": "LKO"},
    {"train_no": "12004", "train_name": "New Delhi Shatabdi",  "source": "LKO",  "destination": "NDLS"},
    {"train_no": "12015", "train_name": "Ajmer Shatabdi",      "source": "NDLS", "destination": "AII"},
    {"train_no": "12013", "train_name": "Amritsar Shatabdi",   "source": "NDLS", "destination": "ASR"},
    {"train_no": "12029", "train_name": "Swarna Shatabdi",     "source": "NDLS", "destination": "CDG"},
    {"train_no": "12137", "train_name": "Punjab Mail",         "source": "CSTM", "destination": "FZR"},
    {"train_no": "12621", "train_name": "Tamil Nadu Express",  "source": "NDLS", "destination": "MAS"},
    {"train_no": "12622", "train_name": "Tamil Nadu Express",  "source": "MAS",  "destination": "NDLS"},
]